In [1]:
import numpy as np

In [2]:
# Paprastas 1D masyvas (vienos dimensijos)
a = np.array([10, 20, 30, 40])
 
print("a =", a)
print("a.ndim  =", a.ndim)   # dimensijų skaičius
print("a.shape =", a.shape)  # forma
print("a.size  =", a.size)   # elementų kiekis
print("a.dtype =", a.dtype)  # duomenų tipas

a = [10 20 30 40]
a.ndim  = 1
a.shape = (4,)
a.size  = 4
a.dtype = int64


In [3]:
# 2D masyvas (dvi dimensijos, dažnai vadinamas matrica)
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print("b =\n", b)
print("b.ndim  =", b.ndim)
print("b.shape =", b.shape)  # 2 eilutės, 3 stulpeliai
print("b.size  =", b.size)   # 2 * 3 = 6 elementai
print("b.dtype =", b.dtype)

[[1 2 3]
 [4 5 6]]
b =
 [[1 2 3]
 [4 5 6]]
b.ndim  = 2
b.shape = (2, 3)
b.size  = 6
b.dtype = int64


In [4]:
x = np.array([5, 10, 15])
y = np.array([[1, 2], [3, 4]])
 
print("x =", x)
print("y =\n", y)

x = [ 5 10 15]
y =
 [[1 2]
 [3 4]]


In [5]:
ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3
 
print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)

ones_1d = [1. 1. 1. 1. 1.]
ones_2d =
 [[1. 1. 1.]
 [1. 1. 1.]]
ones_2d.dtype = float64


In [6]:
ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3
 
print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)

ones_1d = [1. 1. 1. 1. 1.]
ones_2d =
 [[1. 1. 1.]
 [1. 1. 1.]]
ones_2d.dtype = float64


In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
seq1 = np.arange(0, 10)        # 0, 1, 2, ..., 9
seq2 = np.arange(2, 11, 2)     # 2, 4, 6, 8, 10
 
print("seq1 =", seq1)
print("seq2 =", seq2)

seq1 = [0 1 2 3 4 5 6 7 8 9]
seq2 = [ 2  4  6  8 10]


In [11]:
lin1 = np.linspace(0, 1, 5)      # 5 reikšmės nuo 0 iki 1
lin2 = np.linspace(10, 20, 3)    # 10, 15, 20
 
print("lin1 =", lin1)
print("lin2 =", lin2)

lin1 = [0.   0.25 0.5  0.75 1.  ]
lin2 = [10. 15. 20.]


In [ ]:
r = np.arange(1, 7)   # [1, 2, 3, 4, 5, 6]
 
print("r =", r)
print("r.shape =", r.shape)

r = [1 2 3 4 5 6]
r.shape = (6,)


In [13]:
# Formos pakeitimas į 2x3
r_2x3 = r.reshape(2, 3)
 
print("r_2x3 =\n", r_2x3)
print("r_2x3.shape =", r_2x3.shape)

r_2x3 =
 [[1 2 3]
 [4 5 6]]
r_2x3.shape = (2, 3)
