In [1]:
import numpy as np

In [2]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
add_row = np.array([10, 20, 30])  # forma (3,)
 
# Vektorius pridedamas prie kiekvienos eilutės (eilutė po eilutės)
result = mat + add_row
 
print("mat =\n", mat)
print("add_row =", add_row)
print("mat + add_row =\n", result)

mat =
 [[1 2 3]
 [4 5 6]]
add_row = [10 20 30]
mat + add_row =
 [[11 22 33]
 [14 25 36]]


In [3]:
A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A =\n", A)
print("B =\n", B)
 
# Elementų lygio sudėtis ir daugyba
print("A + B =\n", A + B)
print("A * B (element-wise) =\n", A * B)

A =
 [[1 2]
 [3 4]]
B =
 [[10 20]
 [30 40]]
A + B =
 [[11 22]
 [33 44]]
A * B (element-wise) =
 [[ 10  40]
 [ 90 160]]


In [4]:
# Matricų sandauga su @
A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A @ B =\n", A @ B)

A @ B =
 [[ 70 100]
 [150 220]]


In [5]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M * 10 =\n", M * 10)
print("M + 1 =\n", M + 1)

M =
 [[2 4 6]
 [1 3 5]]
M * 10 =
 [[20 40 60]
 [10 30 50]]
M + 1 =
 [[3 5 7]
 [2 4 6]]


In [6]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M.T =\n", M.T)
print("M.shape =", M.shape)
print("M.T.shape =", M.T.shape)

M =
 [[2 4 6]
 [1 3 5]]
M.T =
 [[2 1]
 [4 3]
 [6 5]]
M.shape = (2, 3)
M.T.shape = (3, 2)


In [9]:
vals = np.array([-2.7, -1.2, 0.0, 1.4, 3.9])
 
print("vals =", vals)
print("abs =", np.abs(vals))
print("round(1) =", np.round(vals))
print("clip [0, 3] =", np.clip(vals, 0, 3))

vals = [-2.7 -1.2  0.   1.4  3.9]
abs = [2.7 1.2 0.  1.4 3.9]
round(1) = [-3. -1.  0.  1.  4.]
clip [0, 3] = [0.  0.  0.  1.4 3. ]


In [10]:
pos = np.array([1, 4, 9, 16])
 
print("pos =", pos)
print("sqrt =", np.sqrt(pos))
print("log =", np.log(pos))
print("exp =", np.exp(np.array([0, 1, 2])))

pos = [ 1  4  9 16]
sqrt = [1. 2. 3. 4.]
log = [0.         1.38629436 2.19722458 2.77258872]
exp = [1.         2.71828183 7.3890561 ]


In [11]:
data = np.array([5, 2, 9, 1, 7])
 
print("data =", data)
print("sum =", data.sum())
print("mean =", data.mean())
print("min =", data.min())
print("max =", data.max())
print("median =", np.median(data))
print("std =", data.std())
print("var =", data.var())

data = [5 2 9 1 7]
sum = 24
mean = 4.8
min = 1
max = 9
median = 5.0
std = 2.9933259094191533
var = 8.96


In [13]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
 
print("mat =\n", mat)
print("Vidurkis pagal stulpelius (axis=0):", mat.mean(axis=0))
print("Vidurkis pagal eilutes (axis=1):", mat.mean(axis=1))

mat =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vidurkis pagal stulpelius (axis=0): [4. 5. 6.]
Vidurkis pagal eilutes (axis=1): [2. 5. 8.]


In [14]:
scores = np.array([40, 55, 70, 90, 30])
 
passed = scores >= 60
 
print("scores =", scores)
print("passed =", passed)
 
print("any passed =", passed.any())
print("all passed =", passed.all())
print("passed count =", passed.sum())

scores = [40 55 70 90 30]
passed = [False False  True  True False]
any passed = True
all passed = False
passed count = 2


In [15]:
prices = np.array([9.99, 14.50, 3.20, 25.00, 7.80])
 
mask = prices > 10
high_prices = prices[mask]
 
print("prices =", prices)
print("mask =", mask)
print("high_prices =", high_prices)
print("high_prices count =", mask.sum())
print("high_prices mean =", high_prices.mean())

prices = [ 9.99 14.5   3.2  25.    7.8 ]
mask = [False  True False  True False]
high_prices = [14.5 25. ]
high_prices count = 2
high_prices mean = 19.75
