In [1]:
import numpy as np

In [2]:
a = np.arange(1, 13)  # 1..12
print("a =", a)
print("a.shape =", a.shape)
print("a.size =", a.size)

a = [ 1  2  3  4  5  6  7  8  9 10 11 12]
a.shape = (12,)
a.size = 12


In [3]:
# Formos pakeitimas į 3x4
a_3x4 = a.reshape(3, 4)
print("a_3x4 =\n", a_3x4)
print("a_3x4.shape =", a_3x4.shape)

a_3x4 =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a_3x4.shape = (3, 4)


In [4]:
# Automatinis vienos dimensijos parinkimas su -1
a_auto = a.reshape(2, -1)   # 2 eilutės, stulpelių skaičius apskaičiuojamas automatiškai
print("a_auto =\n", a_auto)
print("a_auto.shape =", a_auto.shape)

a_auto =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a_auto.shape = (2, 6)


In [5]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
flat = m.flatten()
rav = m.ravel()
 
print("m =\n", m)
print("flatten() =", flat)
print("ravel()   =", rav)

m =
 [[1 2 3]
 [4 5 6]]
flatten() = [1 2 3 4 5 6]
ravel()   = [1 2 3 4 5 6]


In [6]:
# Pavyzdys, kaip keitimas gali elgtis skirtingai
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
flat = m.flatten()
rav = m.ravel()
 
flat[0] = 999
rav[1] = 888
 
print("Po pakeitimų:")
print("m =\n", m)          # ravel pakeitimas dažnai persiduoda į originalą
print("flat =", flat)      # flatten yra atskira kopija
print("rav  =", rav)

Po pakeitimų:
m =
 [[  1 888   3]
 [  4   5   6]]
flat = [999   2   3   4   5   6]
rav  = [  1 888   3   4   5   6]


In [7]:
arr = np.arange(1, 13)  # 1..12
 
parts = np.split(arr, 3)  # 12 elementų dalinami į 3 lygias dalis po 4
 
print("arr =", arr)
print("split į 3 dalis:")
for i, p in enumerate(parts, start=1):
    print(f"  dalis {i}:", p)

arr = [ 1  2  3  4  5  6  7  8  9 10 11 12]
split į 3 dalis:
  dalis 1: [1 2 3 4]
  dalis 2: [5 6 7 8]
  dalis 3: [ 9 10 11 12]
